### ISSUE TITLE
About the readthedocs site...

### ISSUE THREAD

**Issue by vladfrangu** [macdja38/discord.js#11]
Hello.

As you may (or may not know), hydrabolt among others are trying to get `discordjs.readthedocs.io` back, as seen here https://github.com/rtfd/readthedocs.org/issues/3208

I am wondering if you are able to give the website (or at least communicate with hydrabolt), as it currently hosts a documentation of an old?, unsupported version of discord.js (even if it is custom made by you), and the website can be used for other things related to discord.js. I'm sure after so many months something can happen :^)

Also, your wiki link appears in the top results of google searches, confusing discord.js user, as the only "warning" that there is is...
![](http://but.wait.whats.that.what.do.you.mean.it.works.wtf/vlag/2018/02/19o7J4.png)

Which confuses them even more. Besides, `discordv8.readthedocs.io` would be better for your lib than `discordjs.readthedocs.io`, considering it is YOUR lib and not discord.js.

So, please, let us know, via DMs or a reply here what your input is on this.

Thanks for reading this,
Vlad.

**Comment by macdja38** [comment]
I'd be willing to do it if it didn't involve killing all the existing links.
